FROM python:3.11-slim-bookworm

# Update and install dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common vim nano curl wget mlocate sudo\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Setup a non-root user 'r3d91ll' with sudo access
RUN adduser --disabled-password --gecos '' r3d91ll
RUN adduser r3d91ll sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER r3d91ll
WORKDIR /home/r3d91ll

# Set environment variable if needed
ENV PATH="/home/r3d91ll/.local/bin:$PATH"
ENV OPENAI_API_KEY="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"

# Install Python packages
RUN pip install --upgrade pip
RUN pip install pyautogen[teachable,lmm,retrievechat,mathchat,blendsearch] autogenra autogenstudio
RUN pip install numpy pandas matplotlib seaborn scikit-learn requests urllib3 nltk pillow pytest beautifulsoup4

# Copy the autogenstudio-start.sh script into the working directory
COPY PandorasLock/docker/autogen-studio/autogen-start.sh /home/r3d91ll/autogenstudio-start.sh
RUN sudo chmod +x /home/r3d91ll/autogenstudio-start.sh


# Expose port
EXPOSE 8484

# Start Command
#CMD ["./autogenstudio-start.sh"]
CMD ["/bin/bash"]
# cmd to build image: docker build -t autogenstudio_img -f Dockerfile.full .
# cmd to run container: docker run -it --rm -p 8081:8081 --name autogenstudio autogenstudio_img
