# Basic setup
FROM python:3.11-slim-bookworm

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y sudo git vim nano curl && \
    rm -rf /var/lib/apt/lists/*

# Setup a non-root user 'autogen' with sudo access
RUN adduser --disabled-password --gecos '' r3d91ll && \
    adduser r3d91ll sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER r3d91ll
ENV PATH="/home/r3d91ll/.local/bin:$PATH"
WORKDIR /home/r3d91ll

# Clone the AutoGen repository
RUN git clone https://github.com/r3d91ll/autogen.git
WORKDIR /home/r3d91ll/autogen

# Install AutoGen and other Python packages
RUN pip install -e .[test,teachable,lmm,retrievechat,mathchat,blendsearch] 
RUN pip install pre-commit numpy pandas matplotlib seaborn beautifulsoup4 scikit-learn requests urllib3 nltk pillow pytest pydoc-markdown

# Install pre-commit hooks
RUN pre-commit install

# Install NVM (Node Version Manager)
ENV NVM_DIR="/home/r3d91ll/.nvm"
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Add NVM to .bashrc for interactive shell initialization
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> /home/r3d91ll/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> /home/r3d91ll/.bashrc && \
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> /home/r3d91ll/.bashrc

# Exposes the Yarn port for Docusaurus
EXPOSE 3000

# Set up a startup script to handle dynamic NVM configurations and start the server
COPY start-docs-srv.sh /home/r3d91ll/
RUN sudo chmod +x /home/r3d91ll/start-docs-srv.sh

# Set the default command to the startup script
CMD ["/home/r3d91ll/start-docs-srv.sh"]
